### ISSUE TITLE
Read only bytebuffer

### ISSUE THREAD

**Issue by lalberge** [Terah-/rust-bytebuffer#10]
Hi,
I appreciate your lib (which I use for serialization/deserialization purposes), but there is a major drawback for my use. When you read from an existing slice &[u8] you deep copy the memory in `from_bytes` function which is not efficient if you treat big slices. I have implemented a read-only version of your lib to handle deserialization. It would be great to have an implementation of read/write for &mut [u8] and read-only for &[u8] data containers. You would consider a contribution to your project?
Thank you,
Leo

**Comment by terahlunah** [comment]
Hi Leo !
I'm glad to know this lib is useful to you. 
Contribution is really appreciated, please submit a PR with your implementation to handle read-only slices as you do have the code ready ;)

**Comment by terahlunah** [comment]
Implemented a `ByteReader` for  `&[u8]` in https://github.com/terahlunah/bytebuffer/commit/7f8b226aefaa2c2140b7dd3ae08086a830fae174.

I can't see a case where a &mut [u8] would be needed so I'll close this issue. But feel free to open a new one if you have a usecase in mind.
