### ISSUE TITLE
missing read float 16

### ISSUE THREAD

**Issue by hYdos** [Terah-/rust-bytebuffer#17]
Even though this type is not in rust std, It makes it less convenient to read. Is it possible this is implemented in the future somehow?

**Comment by terahlunah** [comment]
I added support for [half](https://crates.io/crates/half/) 16 bits floats in this commit https://github.com/terahlunah/bytebuffer/commit/60a4c3190a9aeea90194498c0b692e4b2118be4e

It's available in `bytebuffer = "2.2.0"`

Let me now if it covers all your needs

**Comment by terahlunah** [comment]
Closing this for now, feel free to reopen if needed. @hYdos
