### ISSUE TITLE
Set the endian of a bytebuffer

### ISSUE THREAD

**Issue by Thalamos** [Terah-/rust-bytebuffer#4]
As for now the bytebuffer only reads and writes in big endian order. In some cases one might actually work on the data using little endian (I'm currently facing this problem with a old archive file type). So I would consider adding a way to change the buffers order for example using a set_endian method.

**Comment by terahlunah** [comment]
Good point, I'll add that option.
Or you can submit a PR if you want to :)

**Comment by Thalamos** [comment]
Alright I gonna work on that and submit the PR the next days. Thanks for your fast response.

**Comment by terahlunah** [comment]
Np, I'm glad this lib is useful to someone else :)
Don't hesitate to ask if you need anything !
